// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the GNU Affero General Public License, Version 3. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

export {
    dueDayOffsetMinutes,
    isReminderInstantList,
    isReminderSet,
    isStatableReminderLead,
    isStatableReminderSet,
    longestReminderLead,
    mostRemindersOnOneRecord,
} from './reminders';
export {
    acceptCalendarEvent,
    amendCalendarEvent,
    calendarEventAcceptanceRoute,
    calendarEventDraftRoute,
    calendarEventRoute,
    calendarEventsPerWindow,
    calendarRoute,
    deleteCalendarEvent,
    describedAt,
    draftCalendarEvent,
    isCalendarEventOrigin,
    mostCalendarEventsPerWindow,
    parseCalendarEvent,
    readCalendarEvent,
    readCalendarWindow,
    readsCalendarDescriptions,
    recordCalendarEvent,
    type CalendarEvent,
    type CalendarEventAmendment,
    type CalendarEventDraft,
    type CalendarEventDrafting,
    type CalendarEventOrigin,
    type CalendarEventRecord,
    type CalendarEventRemoval,
    type CalendarEventWrite,
    type CalendarWindow,
    type CalendarWriteOutcome,
} from './calendar';
export {
    clientPreferencesRoute,
    isNotificationTime,
    longestNotificationSeconds,
    longestPreferencesAnswer,
    readClientPreferences,
    shortestNotificationSeconds,
    unsetClientPreferences,
    writeClientPreferences,
    type ClientMessageView,
    type ClientPreferences,
    type ClientThemePreference,
} from './clientPreferences';
export {
    contactCorrespondenceRoute,
    mostCorrespondenceEntries,
    readContactCorrespondence,
    type ContactCorrespondence,
    type CorrespondingDocument,
    type CorrespondingThread,
} from './contactCorrespondence';
export {
    collectedContactsRoute,
    contactPromotionRoute,
    contactRoute,
    contactsPerPage,
    contactsRoute,
    eraseContact,
    mostContactsPerPage,
    promoteContact,
    readCollectedContacts,
    readContact,
    readOwnContacts,
    recordContact,
    type Contact,
    type ContactErasure,
    type ContactOrigin,
    type ContactPage,
    type ContactRecord,
    type ContactWrite,
    type ContactWriteOutcome,
} from './contacts';
export { resolveDeploymentEntry, type DeploymentEntryRefusal, type DeploymentEntryResult } from './deployment';
export {
    deploymentSessionRoute,
    mailPermissions,
    readDeploymentSession,
    type DeploymentSession,
    type MailFathomPermission,
} from './deploymentSession';
export {
    citedPassagesRoute,
    mostCitedPassages,
    readCitations,
    readCitedPassages,
    type CitedFragment,
    type CitedMessage,
    type CitedPassage,
    type CitedPassageOutcome,
    type ResolvedCitation,
} from './citedPassages';
export {
    answerBlockTypes,
    discoveryRunRoute,
    discoveryRunsRoute,
    readDiscoveryRunTail,
    startDiscoveryRun,
    stopDiscoveryRun,
    understoodPlanSchemaVersion,
    type AnswerBlock,
    type AnswerBlockType,
    type DiscoveryRetrievalProgress,
    type DiscoveryRunAsk,
    type DiscoveryRunCeilings,
    type DiscoveryRunEnding,
    type DiscoveryRunEvent,
    type DiscoveryRunSpend,
} from './discoveryRun';
export {
    agentConversationArchiveRoute,
    agentConversationRoute,
    agentConversationsRoute,
    answerAgentProposal,
    archiveAgentConversation,
    askAgent,
    deleteAgentConversation,
    listAgentConversations,
    readAgentConversation,
    restoreAgentConversation,
    steerAgentRun,
    stopAgentRun,
    type AgentAnswerOutcome,
    type AgentConversationEntry,
    type AgentConversationPage,
    type AgentConversationSummary,
    type AgentMessagePosted,
    type AgentMessageScope,
    type AgentProposalDecision,
    type AgentProposalState,
} from './agentConversations';
export { failureReasonForStatus, type ClientFailure, type ClientFailureReason, type ClientResult } from './failure';
export type {
    AnswerConfidence,
    AttachmentAvailability,
    AttachmentEntry,
    BlockEvidence,
    BlockParticipant,
    BlockSupport,
    CitationTarget,
    CitedSourceKind,
    ComposedDraft,
    ConflictingClaim,
    ConversationStanding,
    DeclaredSource,
    DraftDisposition,
    EventProposal,
    EvidenceEntry,
    FactTableCell,
    FactTableColumn,
    FactTableRow,
    PersonEntry,
    SourceFreshness,
    SourceMedium,
    SourceStaleness,
    SuggestedAction,
    SuggestedActionImpact,
    SuggestedActionKind,
    SynthesizedAnswer,
    TaskProposal,
    ThreadCommitment,
    ThreadStatement,
    TimelineEntry,
    UnreadableSource,
} from './presentationBlocks';
export {
    type MailEnrichment,
    type MailEnrichmentAspect,
    type MailEnrichmentMark,
    type MailEnrichmentSource,
} from './mailEnrichment';
export {
    cleanedMailBodyRoute,
    mailBodyRoute,
    readCleanedMailBody,
    readMailBody,
    type CleanedMailBody,
    type MailBlockAlignment,
    type MailBody,
    type MailBodyAsk,
    type MailBodyAvailability,
    type MailBodyCleaning,
    type MailBodyText,
    type MailBodyTruncation,
    type MailDocument,
    type MailDocumentBlock,
    type MailDocumentLink,
    type MailDocumentRefusal,
    type MailHeadingBlock,
    type MailImageBlock,
    type MailInlineImage,
    type MailInlineRun,
    type MailLinkDeception,
    type MailListBlock,
    type MailListItem,
    type MailParagraphBlock,
    type MailPreformattedBlock,
    type MailQuoteBlock,
    type MailTableBlock,
    type MailTableCell,
    type MailTableColumn,
    type MailTableRow,
    type MailTextEmphasis,
    type MailUnimplementedBlock,
} from './mailBody';
export {
    mailAccountsRoute,
    readMailAccounts,
    type MailAccount,
    type MailAccountDirectory,
    type MailSynchronizationState,
} from './mailAccounts';
// `mailDraftAttachmentUploadRequest` is deliberately unpublished, for the reason the download's own request is:
// composed by a caller it would carry no trace context and leave no record. `stageMailDraftAttachment` is how a file
// is staged.
export {
    discardMailDraft,
    mailDraftAttachmentRoute,
    mailDraftAttachmentsRoute,
    mailDraftRoute,
    mailDraftSendRoute,
    mailDraftsRoute,
    mostAttachmentsInDraft,
    mostRecipientsInDraft,
    reviseMailDraft,
    sendMailDraft,
    stageMailDraftAttachment,
    unstageMailDraftAttachment,
    writeMailDraft,
    type MailDraft,
    type MailDraftAnswer,
    type MailDraftComposition,
    type MailDraftRecipient,
    type MailRecipientRole,
    type MailSendOutcome,
    type MailSendRefusal,
    type MailStagedAttachment,
} from './mailDrafts';
export { mailOutboxCancellationRoute, withdrawOutgoingMail, type MailSendWithdrawal } from './mailOutbox';
export {
    isMailFolderRole,
    mailFoldersRoute,
    readMailFolders,
    type MailAccountFolders,
    type MailFolder,
    type MailFolderDirectory,
    type MailFolderRole,
} from './mailFolders';
export {
    createManagedMailFolder,
    deleteManagedMailFolder,
    managedMailFolderDeletionsRoute,
    managedMailFolderMovesRoute,
    managedMailFolderRenamesRoute,
    managedMailFoldersRoute,
    moveManagedMailFolder,
    readManagedMailFolders,
    renameManagedMailFolder,
    type ManagedMailFolder,
    type ManagedMailFolderAct,
    type ManagedMailFolderChange,
    type ManagedMailFolderOutcome,
    type ManagedMailFolderRefusal,
    type ManagedMailFolders,
} from './managedMailFolders';
export {
    declareMailFolder,
    folderDeclarationRoute,
    folderRemovalRoute,
    folderReplacementRoute,
    readFolderConfigurationVersion,
    replaceMailFolder,
    userRecordRoute,
    withdrawMailFolder,
    type DeclaredMailFolder,
    type MailFolderConfigurationOutcome,
} from './mailFolderConfiguration';
// `mailAttachmentRequest` is deliberately unpublished: a caller composing it would compose it outside the span this
// package opens, so the request would carry no trace context and no record would be kept of it. `readMailAttachment`
// is how a download is reached, and the same holds for the portrait requests further down.
export {
    attachmentRefusalForStatus,
    mailAttachmentRoute,
    readMailAttachment,
    type MailAttachmentRefusal,
} from './mailAttachment';
export {
    mailMessageRoute,
    readMailMessage,
    type MailAttachment,
    type MailAuthorAuthentication,
    type MailCarried,
    type MailDeploymentTrust,
    type MailMessage,
    type MailMessageBodyForms,
    type MailMessageHeaders,
    type MailParticipant,
    type MailParticipantRole,
    type MailSenderVerdict,
} from './mailMessage';
export {
    changeMailFlags,
    deleteMail,
    mailDeleteMutationsRoute,
    mailDeleteReleasesRoute,
    mailDeleteWithdrawalsRoute,
    mailFlagMutationsRoute,
    mailMoveMutationsRoute,
    mailMutationRecordsRoute,
    markMailRead,
    moveMail,
    mostMessagesPerMutation,
    mostRecordsPerRead,
    readMailMutationRecords,
    releaseMailDeletes,
    withdrawMailDeletes,
    type MailFlagChange,
    type MailMove,
    type MailMutationChange,
    type MailMutationOutcome,
    type MailMutationRecord,
    type MailMutationRecordState,
    type MailMutationResult,
} from './mailMutations';
export {
    longestSearchPage,
    longestSearchText,
    mailSearchRoute,
    mostSearchResults,
    readMailSearch,
    searchQueryString,
    type MailSearchAttachmentMatch,
    type MailSearchAttachmentSource,
    type MailSearchPage,
    type MailSearchQuery,
    type MailSearchRanking,
    type MailSearchResult,
    type MailSearchRetrieval,
    type MailSearchSegmentKind,
    type MailSemanticSearch,
} from './mailSearch';
export {
    mailSearchPhrasingRoute,
    phraseNotRead,
    readMailSearchPhrase,
    readsMailSearchPhrases,
    type MailSearchPhraseFilters,
    type MailSearchPhraseReading,
} from './mailSearchPhrase';
export {
    draftMailReply,
    draftsMailReplies,
    longestDraftInstruction,
    longestDraftSelection,
    mailReplyDraftingRoute,
    nothingDrafted,
    type MailReplyDraft,
    type MailReplyDraftClaim,
    type MailReplyDraftRecipient,
    type MailReplyDraftRequest,
    type MailReplyDraftSource,
    type MailReplyDrafting,
} from './mailReplyDrafting';
export {
    longestDrawnThreadPage,
    longestThreadPage,
    mailThreadRoute,
    readMailThread,
    threadQueryString,
    type MailThreadMessage,
    type MailThreadPage,
    type MailThreadParticipant,
} from './mailThread';
export {
    mailThreadStateRoute,
    readMailThreadState,
    type MailThreadState,
    type MailThreadStateAspect,
    type MailThreadStateCoverage,
    type MailThreadStateEntry,
    type MailThreadStateSource,
} from './mailThreadState';
export {
    longestTimelinePage,
    mailTimelineRoute,
    readMailTimeline,
    timelineQueryString,
    type MailTimelineEntry,
    type MailTimelineOrder,
    type MailTimelinePage,
    type MailTimelinePageDirection,
    type MailTimelineQuery,
} from './mailTimeline';
export {
    deleteNotifications,
    longestNotificationPage,
    markAllNotificationsRead,
    markAllNotificationsReadRoute,
    mostNotificationsErasedAtOnce,
    notificationDeletionsRoute,
    notificationsRoute,
    readNotifications,
    readUnreadNotificationCount,
    setNotificationRead,
    unreadNotificationCountRoute,
    type ClientNotification,
    type ErasedNotifications,
    type MarkedNotifications,
    type NotificationCause,
    type NotificationKind,
    type NotificationPage,
    type NotificationReadState,
    type NotificationScreen,
    type NotificationStatement,
    type NotificationTarget,
} from './notifications';
export {
    changeOwnDisplayName,
    longestDisplayNameAnswer,
    ownDisplayNameRoute,
    readOwnDisplayName,
    type OwnDisplayName,
    type OwnDisplayNameChange,
} from './ownDisplayName';
// `readOwnPortraitRequest` and the two beside it are deliberately unpublished, for the reason the download above gives.
export {
    isPortraitImageType,
    largestPortraitOctets,
    ownPortraitRoute,
    portraitImageTypes,
    readOwnPortrait,
    removeOwnPortrait,
    replaceOwnPortrait,
    type PortraitImageType,
} from './ownPortrait';
export {
    changeOwnTimeZone,
    longestTimeZoneAnswer,
    ownTimeZoneRoute,
    readOwnTimeZone,
    reportedTimeZone,
    type OwnTimeZone,
    type OwnTimeZoneChange,
} from './ownTimeZone';
export { mostReconnectionAttempts, reconnectionDelay } from './reconnection';
export {
    followRun,
    silentRunPollInterval,
    type FollowedRun,
    type FollowedRunEvent,
    type RunFollowingSchedule,
    type RunTail,
    type RunTailReading,
    type RunToFollow,
} from './runFollowing';
export {
    endSession,
    parseMintedSession,
    renewSession,
    sessionExchangeRoute,
    sessionRevocationRoute,
    type MintedSession,
} from './sessionToken';
export { clientRoutePrefix, headersFor, routeFor, type ClientSession, type DeploymentAddress } from './session';
export {
    hubAddressFor,
    mostNamedSignalEmails,
    openSignalStream,
    parseClientSignal,
    readSignalTicket,
    signalHubRoute,
    signalMethod,
    signalTicketParameter,
    signalTicketRoute,
    type ClientSignal,
    type MailFathomSignalChannel,
    type SignalChannelHandle,
    type SignalChannelOpening,
    type SignalledFlags,
    type SignalNotificationKind,
    type SignalStream,
    type SignalStreamSchedule,
    type SignalTicket,
} from './signals';
export {
    defaultTelemetryLevel,
    isDeploymentTelemetryLevel,
    recordDownTo,
    severityOf,
    telemetryEndpoints,
    telemetryName,
    worthRecording,
    writeClientEvent,
    type ClientEvent,
    type ClientEventRecord,
    type DeploymentTelemetryLevel,
} from './telemetry';
export {
    acceptTask,
    arrangesDays,
    eraseTask,
    isTaskOrigin,
    layOutToday,
    longestTaskTitle,
    mostTasksPerPage,
    parseTask,
    proposedTasksRoute,
    readOwnTasks,
    readProposedTasks,
    recordTask,
    reviseTask,
    setTaskCompletion,
    taskAcceptanceRoute,
    taskCompletionRoute,
    taskRoute,
    tasksPerPage,
    tasksRoute,
    todayLayoutRoute,
    type DayLayout,
    type DayLayoutOutcome,
    type DayLayoutPlacement,
    type PersonalTask,
    type PersonalTaskErasure,
    type PersonalTaskOrigin,
    type PersonalTaskPage,
    type PersonalTaskRecord,
} from './tasks';
export { reachDeployment, signIn, type DeploymentGreeting, type SignInOutcome, type SignInRefusal } from './signIn';
export {
    longestSignInMethodsAnswer,
    mostAuthorizationServers,
    originOf,
    ownProviderName,
    protectedResourceMetadataRoute,
    readProtectedResource,
    readSignInMethods,
    signInMethodsRoute,
    type ProtectedResource,
    type SignInAuthorizationServer,
    type SignInMethods,
} from './signInMethods';
export {
    authorizationRequestAddress,
    discoveryAddresses,
    longestIssuedToken,
    readAuthorizationServer,
    redeemAuthorizationCode,
    refreshAccessToken,
    revokeRefreshToken,
    type AuthorizationRequest,
    type AuthorizationServerMetadata,
    type IssuedAccessToken,
    type TokenOutcome,
} from './oauthSignIn';
export { longestResponseBody, type ClientRequest, type ClientResponse, type MailFathomTransport } from './transport';
