<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailMcp.AI\MailMcp.AI.csproj" />
    <ProjectReference Include="..\MailMcp.Application\MailMcp.Application.csproj" />
    <ProjectReference Include="..\MailMcp.Domain\MailMcp.Domain.csproj" />
    <ProjectReference Include="..\MailMcp.Infrastructure\MailMcp.Infrastructure.csproj" />
    <ProjectReference Include="..\MailMcp.Mcp\MailMcp.Mcp.csproj" />
  </ItemGroup>
</Project>
