// Copyright © 2026 Krzysztof Kasprowicz

using MailMcp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using NpgsqlTypes;
using Xunit;

namespace MailMcp.Infrastructure.UnitTests;

/// <summary>
/// Asserts the shape of the lexical index the schema is generated from. The model is built in memory by the real
/// PostgreSQL provider and no connection is opened, so this states what the column and index are declared to be;
/// whether PostgreSQL then matches a query against them is an integration question that specification 20 answers.
/// </summary>
public sealed class EmailSearchDocumentModelTests
{
    /// <summary>The vector is generated by PostgreSQL, so nothing MailMcp writes can leave it describing other text.</summary>
    [Fact]
    public void EmailSearchDocumentModel_SearchVector_IsGeneratedByTheDatabase()
    {
        // Act
        var searchVector = SearchDocumentProperty(nameof(EmailSearchDocumentEntity.SearchVector));

        // Assert
        Assert.Equal(typeof(NpgsqlTsVector), searchVector.ClrType);
        Assert.Equal(ValueGenerated.OnAddOrUpdate, searchVector.ValueGenerated);
    }

    /// <summary>Subject, participants, and the trimmed body are one document, which is what a query matches against.</summary>
    [Fact]
    public void EmailSearchDocumentModel_SearchVector_CoversTheSubjectParticipantsAndTrimmedBody()
    {
        // Act
        var indexedProperties = SearchDocumentProperty(nameof(EmailSearchDocumentEntity.SearchVector))
            .GetTsVectorProperties();

        // Assert
        Assert.NotNull(indexedProperties);
        Assert.Equal(
            [
                nameof(EmailSearchDocumentEntity.SubjectText),
                nameof(EmailSearchDocumentEntity.ParticipantAddresses),
                nameof(EmailSearchDocumentEntity.BodyText),
            ],
            indexedProperties);
    }

    /// <summary>The configuration is named rather than inherited, which is both what makes the expression immutable and what fixes what the index holds.</summary>
    [Fact]
    public void EmailSearchDocumentModel_SearchVector_NamesTheConfiguredTextSearchConfiguration()
    {
        // Act
        var textSearchConfiguration = SearchDocumentProperty(nameof(EmailSearchDocumentEntity.SearchVector))
            .GetTsVectorConfig();

        // Assert
        Assert.Equal(PostgresTextSearchConfiguration.Default.Value, textSearchConfiguration);
    }

    /// <summary>A <c>tsvector</c> lookup is a containment test, which only an inverted index can serve.</summary>
    [Fact]
    public void EmailSearchDocumentModel_SearchVectorIndex_UsesTheInvertedIndexMethod()
    {
        // Arrange
        using var context = CreateContext();

        // Act
        var index = SearchDocumentEntityType(context)
            .GetIndexes()
            .FirstOrDefault(candidate => candidate.GetDatabaseName() == MailMcpDbContext.EmailSearchDocumentVectorIndexName);

        // Assert
        Assert.NotNull(index);
        Assert.Equal([nameof(EmailSearchDocumentEntity.SearchVector)], index.Properties.Select(property => property.Name));
        Assert.Equal("GIN", index.GetMethod());
    }

    /// <summary>Deleting a message deletes everything derived from it, which is what keeps erasure complete.</summary>
    [Fact]
    public void EmailSearchDocumentModel_OwningEmailDeleted_CascadesToTheDerivedDocument()
    {
        // Arrange
        using var context = CreateContext();

        // Act
        var foreignKey = Assert.Single(SearchDocumentEntityType(context).GetForeignKeys());

        // Assert
        Assert.Equal(DeleteBehavior.Cascade, foreignKey.DeleteBehavior);
        Assert.Equal(typeof(StoredEmailEntity), foreignKey.PrincipalEntityType.ClrType);
    }

    /// <summary>The derived text is a table of its own, so a timeline query carries no body and no vector.</summary>
    [Fact]
    public void EmailSearchDocumentModel_MetadataTable_HoldsNoDerivedText()
    {
        // Arrange
        using var context = CreateContext();

        // Act
        var storedEmail = context.Model.FindEntityType(typeof(StoredEmailEntity))!;

        // Assert
        Assert.DoesNotContain(
            storedEmail.GetProperties(),
            property => property.ClrType == typeof(NpgsqlTsVector));
        Assert.NotEqual(
            storedEmail.GetTableName(),
            SearchDocumentEntityType(context).GetTableName());
    }

    /// <summary>The indexed subject copy is bounded, because the whole document has to stay inside PostgreSQL's limit.</summary>
    [Fact]
    public void EmailSearchDocumentModel_IndexedSubject_IsBounded()
    {
        // Act
        var subjectText = SearchDocumentProperty(nameof(EmailSearchDocumentEntity.SubjectText));

        // Assert
        Assert.Equal(EmailSearchDocumentEntity.MaximumIndexedSubjectLength, subjectText.GetMaxLength());
    }

    private static IProperty SearchDocumentProperty(string propertyName)
    {
        using var context = CreateContext();

        var property = SearchDocumentEntityType(context).FindProperty(propertyName);

        Assert.NotNull(property);

        return property;
    }

    /// <summary>
    /// Reads the design-time model rather than <c>DbContext.Model</c>, because the runtime model is trimmed to what a
    /// query needs and throws for the index configuration a schema is generated from.
    /// </summary>
    private static IEntityType SearchDocumentEntityType(MailMcpDbContext context) =>
        context.GetService<IDesignTimeModel>().Model.FindEntityType(typeof(EmailSearchDocumentEntity))!;

    private static MailMcpDbContext CreateContext() =>
        new MailMcpDbContextDesignTimeFactory().CreateDbContext([]);
}
