// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using MailFathom.Application.Emails;
using MailFathom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace MailFathom.Infrastructure.UnitTests;

/// <summary>
/// Asserts what the search adapter actually sends to PostgreSQL. The command is generated by the real provider against
/// the real model and no connection is opened, which is the only place the parameterization claim is checkable without
/// a database: an in-memory repository generates no SQL, so a test feeding it metacharacters would pass against a
/// vulnerable adapter and prove nothing. Whether the server then uses the GIN index is a query-plan question
/// specification 20 answers.
/// </summary>
public sealed class StoredEmailSearchIndexReaderCommandTests
{
    /// <summary>A query text carrying everything an injection attempt would: quotes, a statement terminator, a comment.</summary>
    private const string HostileQueryText = "'; DROP TABLE stored_emails; -- \" \\ %";

    /// <summary>Whatever a caller writes stays one value, so nothing in it can become part of the command.</summary>
    [Fact]
    public void RankedHitsQuery_HostileQueryText_ReachesPostgresAsAParameter()
    {
        // Act
        var command = GeneratedCommand(QueryTextFor(HostileQueryText));

        // Assert
        Assert.Contains(HostileQueryText, ParameterDeclarations(command), StringComparison.Ordinal);
        Assert.DoesNotContain(HostileQueryText, CommandBody(command), StringComparison.Ordinal);
        Assert.DoesNotContain("DROP TABLE", CommandBody(command), StringComparison.Ordinal);
    }

    /// <summary>Every full-text operator reads the query from the same parameter, so none of them is a second path in.</summary>
    [Theory]
    [InlineData("@@")]
    [InlineData("ts_rank")]
    [InlineData("ts_headline")]
    public void RankedHitsQuery_EveryFullTextOperator_ReadsTheParameterizedQuery(string sqlOperator)
    {
        // Act
        var statement = CommandBody(GeneratedCommand(QueryTextFor(HostileQueryText)));

        // Assert
        Assert.Contains(sqlOperator, statement, StringComparison.Ordinal);
        Assert.DoesNotContain(HostileQueryText, statement, StringComparison.Ordinal);
    }

    /// <summary>The configuration is the deployment's schema setting, so it is written into the command rather than taken from a request.</summary>
    [Fact]
    public void RankedHitsQuery_TextSearchConfiguration_IsTheOneTheIndexWasBuiltWith()
    {
        // Act
        var command = CommandBody(GeneratedCommand(QueryTextFor("invoice")));

        // Assert
        Assert.Contains($"'{PostgresTextSearchConfiguration.Default.Value}'", command, StringComparison.Ordinal);
    }

    /// <summary>Ranking ties, so the ordering contract appends the timeline key and the window is closed by a limit.</summary>
    [Fact]
    public void RankedHitsQuery_AnyQuery_OrdersByRankThenTheTimelineKeyAndLimitsTheWindow()
    {
        // Act
        var command = CommandBody(GeneratedCommand(QueryTextFor("invoice")));

        // Assert
        Assert.Contains("ORDER BY ts_rank", command, StringComparison.Ordinal);
        Assert.Contains("LIMIT", command, StringComparison.Ordinal);
    }

    /// <summary>The body is cut into extracts by the server, so no column holding it is part of what crosses the boundary.</summary>
    [Fact]
    public void RankedHitsQuery_AnyQuery_SelectsTheHeadlineRatherThanTheBodyText()
    {
        // Act
        var command = GeneratedCommand(QueryTextFor("invoice"));
        var statement = CommandBody(command);
        var selectList = statement[..statement.IndexOf("FROM", StringComparison.Ordinal)];

        // Assert
        Assert.Contains("ts_headline", selectList, StringComparison.Ordinal);
        Assert.DoesNotContain(nameof(EmailSearchDocumentEntity.BodyTextBeforeTrimming), command, StringComparison.Ordinal);
    }

    /// <summary>The bounds reach the server as the option list that cuts the extracts, so PostgreSQL applies them.</summary>
    [Fact]
    public void RankedHitsQuery_ConfiguredSnippetBounds_ReachTheHeadlineOptions()
    {
        // Arrange
        var bounds = EmailSearchSnippetBounds.Create(snippetsPerEmail: 2, wordsPerSnippet: 15);

        // Act
        var command = GeneratedCommand(QueryTextFor("invoice"), bounds);

        // Assert
        Assert.Contains("MaxFragments=2", command, StringComparison.Ordinal);
        Assert.Contains("MaxWords=15", command, StringComparison.Ordinal);
        Assert.Contains("MinWords=5", command, StringComparison.Ordinal);
    }

    /// <summary>
    /// The server marks matches with control characters, never with the markup a caller receives. Whether a fragment
    /// carries a marker is what separates a genuine highlight from the opening words <c>ts_headline</c> falls back to,
    /// and a printable marker cannot answer that — Markdown mail writes <c>**</c> of its own. Text extraction drops
    /// every control character except the tab and the newline, so an indexed body cannot imitate these.
    /// </summary>
    [Fact]
    public void RankedHitsQuery_HighlightMarkers_AreControlCharactersRatherThanPublishedMarkup()
    {
        // Act
        var command = GeneratedCommand(QueryTextFor("invoice"));

        // Assert
        Assert.Contains("StartSel=\"\u0002\"", command, StringComparison.Ordinal);
        Assert.Contains("StopSel=\"\u0003\"", command, StringComparison.Ordinal);
        Assert.DoesNotContain("StartSel=\"**\"", command, StringComparison.Ordinal);
    }

    /// <summary>
    /// The second statement narrows by the selection as well as by the ranked identifiers. PostgreSQL reads each
    /// statement under its own snapshot, so a run committing between them could otherwise pair a summary that fails the
    /// filter with the rank computed while it still passed.
    /// </summary>
    [Fact]
    public void SummaryQuery_AnyWindow_NarrowsByTheSelectionAsWellAsTheRankedIdentifiers()
    {
        // Arrange
        var selection = MailboxEmailSelection.Create(
            MailboxScope.Unrestricted,
            senderAddress: null,
            recipientAddress: null,
            subjectFragment: null,
            receivedOnOrAfter: null,
            receivedBefore: null,
            isRemotelySeen: null,
            hasAttachments: false);

        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        // Act
        var command = StoredEmailSelectionPredicate
            .Matching(context.StoredEmails.AsNoTracking(), selection)
            .Select(StoredEmailSummaryRow.Projection)
            .ToQueryString();

        // Assert
        Assert.Contains(nameof(StoredEmailEntity.AttachmentCount), command, StringComparison.Ordinal);
    }

    /// <summary>The structural filters narrow the same table the listing narrows, through the predicate both share.</summary>
    [Fact]
    public void RankedHitsQuery_StructuralFilters_NarrowTheQueryBeforeAnythingIsRanked()
    {
        // Arrange
        var selection = MailboxEmailSelection.Create(
            MailboxScope.Unrestricted,
            senderAddress: "anna@example.test",
            recipientAddress: null,
            subjectFragment: null,
            receivedOnOrAfter: null,
            receivedBefore: null,
            isRemotelySeen: null,
            hasAttachments: true);

        // Act
        var command = CommandBody(GeneratedCommand(QueryTextFor("invoice"), selection: selection));

        // Assert
        Assert.Contains(nameof(StoredEmailEntity.SenderNormalizedAddress), command, StringComparison.Ordinal);
        Assert.Contains(nameof(StoredEmailEntity.AttachmentCount), command, StringComparison.Ordinal);
    }

    private static EmailSearchQueryText QueryTextFor(string text) => EmailSearchQueryText.Create(text);

    /// <summary>Generates the command the adapter would send, without opening a connection.</summary>
    private static string GeneratedCommand(
        EmailSearchQueryText queryText,
        EmailSearchSnippetBounds? snippetBounds = null,
        MailboxEmailSelection? selection = null)
    {
        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        var reader = new StoredEmailSearchIndexReader(context, PostgresTextSearchConfiguration.Default);

        return reader
            .RankedHitsQuery(
                selection ?? MailboxEmailSelection.Create(
                    MailboxScope.Unrestricted,
                    senderAddress: null,
                    recipientAddress: null,
                    subjectFragment: null,
                    receivedOnOrAfter: null,
                    receivedBefore: null,
                    isRemotelySeen: null,
                    hasAttachments: null),
                queryText,
                snippetBounds ?? EmailSearchSnippetBounds.Default,
                EmailSearchResultLimit.DefaultValue)
            .ToQueryString();
    }

    /// <summary>Drops the parameter declarations EF Core prefixes, leaving the statement those parameters are read by.</summary>
    /// <remarks>
    /// The declarations repeat every parameter's value, so an assertion that a value is absent from the command has to
    /// be made against the statement rather than against the whole listing — otherwise it would fail on the very line
    /// that proves the value is a parameter.
    /// </remarks>
    private static string CommandBody(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? command : command[statementStart..];
    }

    /// <summary>Keeps the parameter declarations EF Core prefixes, which is where a parameterized value appears.</summary>
    private static string ParameterDeclarations(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? string.Empty : command[..statementStart];
    }
}
