// <auto-generated />
using System;
using MailFathom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace MailFathom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MailFathomDbContext))]
    [Migration("20260812170539_RenameRuleExecutionDestinationColumn")]
    partial class RenameRuleExecutionDestinationColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.BackfillPositionEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("LastProcessedStoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("backfill_positions", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DerivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDerivedFromLossyHtml")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoredEmailId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_email_chunks_email_ordinal");

                    b.ToTable("email_chunks", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Defect")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("StoredEmailId");

                    b.ToTable("email_content_repair_requests", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailEmbeddingEntity", b =>
                {
                    b.Property<Guid>("EmailChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmbeddingProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EmailChunkId", "EmbeddingProfileId")
                        .HasName("pk_email_embeddings");

                    b.HasIndex("EmbeddingProfileId", "Dimension")
                        .HasDatabaseName("ix_email_embeddings_profile");

                    b.ToTable("email_embeddings", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_embeddings_dimension", "vector_dims(\"Embedding\") = \"Dimension\"");
                        });
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<long>("MimeByteLength")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RawMime")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoredEmailId");

                    b.ToTable("email_message_contents", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<string>("BodyTextBeforeTrimming")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParticipantAddresses")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SubjectText", "ParticipantAddresses", "BodyText" });

                    b.Property<string>("SubjectText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TextSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("StoredEmailId");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_email_search_documents_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("email_search_documents", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("CorpusRevision")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("StoredEmailId")
                        .HasName("pk_email_spam_classifications");

                    b.ToTable("email_spam_classifications", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationSignalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Observation")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredEmailId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_email_spam_classification_signals_classification_ordinal");

                    b.ToTable("email_spam_classification_signals", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmbeddingProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<string>("DistanceMetric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentityFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("InputCharacterLimit")
                        .HasColumnType("integer");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("NormalizesVector")
                        .HasColumnType("boolean");

                    b.Property<string>("PassageInstruction")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "Dimension")
                        .HasName("ak_embedding_profiles_id_dimension");

                    b.HasIndex("IdentityFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_embedding_profiles_identity_fingerprint");

                    b.HasIndex("LifecycleState")
                        .IsUnique()
                        .HasDatabaseName("ix_embedding_profiles_lifecycle_state")
                        .HasFilter("\"LifecycleState\" IN ('Building', 'Active')");

                    b.ToTable("embedding_profiles", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmbeddingSpendPeriodEntity", b =>
                {
                    b.Property<DateTimeOffset>("PeriodStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PeriodStartsAt");

                    b.Property<long>("ConsumedInputCharacterCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ConsumedInputCharacterCount");

                    b.HasKey("PeriodStartsAt");

                    b.ToTable("embedding_spend_periods", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailAnsweringAuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChatEndpointAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Degradation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InstructionsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "MailboxAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_mail_answering_audit_entries_run_account");

                    b.HasIndex("MailboxAccountId", "CompletedAt", "Id")
                        .HasDatabaseName("ix_mail_answering_audit_entries_account_completed");

                    b.ToTable("mail_answering_audit_entries", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailAnsweringAuditedEmailEntity", b =>
                {
                    b.Property<Guid>("MailAnsweringAuditEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<bool>("WasCited")
                        .HasColumnType("boolean");

                    b.HasKey("MailAnsweringAuditEntryId", "StoredEmailId");

                    b.HasIndex("StoredEmailId");

                    b.ToTable("mail_answering_audited_emails", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HierarchyDelimiter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ResolutionGeneration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MailboxAccountId", "Alias", "ResolutionGeneration")
                        .IsUnique()
                        .HasDatabaseName("ix_mail_folders_account_alias_generation");

                    b.ToTable("mail_folders", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleEvaluationRunEntity", b =>
                {
                    b.Property<string>("MailboxAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ending")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("EvaluatedEmailCount")
                        .HasColumnType("integer");

                    b.Property<int>("MatchedEmailCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Position")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Revision")
                        .HasMaxLength(12)
                        .HasColumnType("character(12)")
                        .IsFixedLength();

                    b.Property<int>("SkippedEmailCount")
                        .HasColumnType("integer");

                    b.HasKey("MailboxAccountId")
                        .HasName("pk_mail_rule_evaluation_runs");

                    b.ToTable("mail_rule_evaluation_runs", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutedActionEntity", b =>
                {
                    b.Property<Guid>("MailRuleExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Mutation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("MutationRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("MailRuleExecutionId", "Position");

                    b.ToTable("mail_rule_executed_actions", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionFailure")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<string[]>("ReadFacts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character(12)")
                        .IsFixedLength();

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxAccountId", "EvaluatedAt", "Id")
                        .HasDatabaseName("ix_mail_rule_executions_account_evaluated");

                    b.HasIndex("StoredEmailId", "EvaluatedAt", "Id")
                        .HasDatabaseName("ix_mail_rule_executions_email_evaluated");

                    b.HasIndex("MailboxAccountId", "RuleName", "EvaluatedAt", "Id")
                        .HasDatabaseName("ix_mail_rule_executions_account_rule_evaluated");

                    b.ToTable("mail_rule_executions", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id")
                        .HasName("PK_mailbox_accounts");

                    b.ToTable("mailbox_accounts", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxMutationAuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DesiredSeenState")
                        .HasColumnType("boolean");

                    b.Property<string>("DestinationFolderPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DestinationHierarchyDelimiter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int?>("FailureCode")
                        .HasColumnType("integer");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mutation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MutationRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("PlacementUid")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlacementUidValidity")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterIdentity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequesterOrigin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceFolderPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SourceHierarchyDelimiter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<long>("SourceUid")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceUidValidity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MutationRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_mailbox_mutation_audit_entries_mutation");

                    b.HasIndex("MailboxAccountId", "CompletedAt", "Id")
                        .HasDatabaseName("ix_mailbox_mutation_audit_entries_account_completed");

                    b.ToTable("mailbox_mutation_audit_entries", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxMutationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AuditTrailEnabled")
                        .HasColumnType("boolean");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool?>("DesiredSeenState")
                        .HasColumnType("boolean");

                    b.Property<string>("DestinationFolderPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DestinationHierarchyDelimiter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int?>("LastFailureCode")
                        .HasColumnType("integer");

                    b.Property<string>("LocalDisposition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("MailFolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mutation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PlacementObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PlacementUid")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlacementUidValidity")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterIdentity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequesterOrigin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("RequiresSourceRemoval")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SourceRemovalObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StageChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StoredEmailId");

                    b.HasIndex("MailboxAccountId", "RecordedAt")
                        .HasDatabaseName("ix_mailbox_mutations_outstanding")
                        .HasFilter("\"Stage\" <> 'Completed'");

                    b.HasIndex("MailboxAccountId", "DestinationFolderPath", "PlacementUidValidity", "PlacementUid")
                        .HasDatabaseName("ix_mailbox_mutations_placement")
                        .HasFilter("\"PlacementObservedAt\" IS NULL");

                    b.HasIndex("MailFolderId", "UidValidity", "Uid", "RequesterOrigin", "RequesterIdentity", "Mutation")
                        .IsUnique()
                        .HasDatabaseName("ix_mailbox_mutations_identity");

                    b.ToTable("mailbox_mutations", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxRefreshTokenEntity", b =>
                {
                    b.Property<string>("MailboxAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DataEncryptionKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("SealedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MailboxAccountId");

                    b.HasIndex("DataEncryptionKeyId")
                        .HasDatabaseName("ix_mailbox_refresh_tokens_data_encryption_key");

                    b.ToTable("mailbox_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<long>("AttachmentTotalSizeOctets")
                        .HasColumnType("bigint");

                    b.Property<bool>("CarriesUnverifiedSignature")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("CcAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("ChunkedTextTruncatedFromCharacterCount")
                        .HasColumnType("integer");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("ContainsUnexpandedTnefPart")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentAvailability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<int>("InlineResourceCount")
                        .HasColumnType("integer");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyFlagged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelySeen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetainedAfterAuthoredDelete")
                        .HasColumnType("boolean");

                    b.Property<long>("MailFolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RemoteExpungeObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RemoteFlagsObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("ReplyToAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("RulesEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SenderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SenderNormalizedAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SizeOctets")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ThreadReferences")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CcAddresses")
                        .HasDatabaseName("ix_stored_emails_cc_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CcAddresses"), "GIN");

                    b.HasIndex("ReplyToAddresses")
                        .HasDatabaseName("ix_stored_emails_reply_to_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ReplyToAddresses"), "GIN");

                    b.HasIndex("SenderNormalizedAddress")
                        .HasDatabaseName("ix_stored_emails_sender");

                    b.HasIndex("ToAddresses")
                        .HasDatabaseName("ix_stored_emails_to_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ToAddresses"), "GIN");

                    b.HasIndex("MailboxAccountId", "Id")
                        .HasDatabaseName("ix_stored_emails_account_identity");

                    b.HasIndex("MailFolderId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_stored_emails_folder_timeline");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("MailFolderId", "ReceivedAt", "Id"), new[] { NullSortOrder.Unspecified, NullSortOrder.NullsLast, NullSortOrder.Unspecified });

                    b.HasIndex("MailFolderId", "RemoteFlagsObservedAt", "Uid")
                        .HasDatabaseName("ix_stored_emails_reconciliation_queue")
                        .HasFilter("\"RemoteExpungeObservedAt\" IS NULL");

                    b.HasIndex("MailFolderId", "UidValidity", "Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_stored_emails_folder_uidvalidity_uid");

                    b.HasIndex("MailboxAccountId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_stored_emails_account_timeline");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("MailboxAccountId", "ReceivedAt", "Id"), new[] { NullSortOrder.Unspecified, NullSortOrder.NullsLast, NullSortOrder.Unspecified });

                    b.HasIndex(new[] { "MailFolderId", "UidValidity", "Uid" }, "ix_stored_emails_awaiting_content")
                        .HasDatabaseName("ix_stored_emails_awaiting_content")
                        .HasFilter("\"ContentAvailability\" = 'AwaitingStorageHeadroom'");

                    b.HasIndex(new[] { "MailboxAccountId", "Id" }, "ix_stored_emails_awaiting_rule_evaluation")
                        .HasDatabaseName("ix_stored_emails_awaiting_rule_evaluation")
                        .HasFilter("\"RulesEvaluatedAt\" IS NULL");

                    b.ToTable("stored_emails", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", b =>
                {
                    b.Property<long>("MailFolderId")
                        .HasColumnType("bigint");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("LastSeenUid")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReconciledThroughModSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("MailFolderId")
                        .HasName("pk_synchronization_checkpoints");

                    b.ToTable("synchronization_checkpoints", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailChunkEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithMany("Chunks")
                        .HasForeignKey("StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("ContentRepairRequest")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailEmbeddingEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.EmailChunkEntity", "EmailChunk")
                        .WithMany("Embeddings")
                        .HasForeignKey("EmailChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.EmbeddingProfileEntity", "EmbeddingProfile")
                        .WithMany("Embeddings")
                        .HasForeignKey("EmbeddingProfileId", "Dimension")
                        .HasPrincipalKey("Id", "Dimension")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_embeddings_embedding_profiles");

                    b.Navigation("EmailChunk");

                    b.Navigation("EmbeddingProfile");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("Content")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("SearchDocument")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("SpamClassification")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationSignalEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationEntity", "Classification")
                        .WithMany("Signals")
                        .HasForeignKey("StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_spam_classification_signals_classifications");

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailAnsweringAuditedEmailEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailAnsweringAuditEntryEntity", null)
                        .WithMany("Emails")
                        .HasForeignKey("MailAnsweringAuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", null)
                        .WithMany()
                        .HasForeignKey("StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", "MailboxAccount")
                        .WithMany("MailFolders")
                        .HasForeignKey("MailboxAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxAccount");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutedActionEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutionEntity", null)
                        .WithMany("Actions")
                        .HasForeignKey("MailRuleExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutionEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", null)
                        .WithMany()
                        .HasForeignKey("StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxMutationEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", "MailFolder")
                        .WithMany()
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithMany("Mutations")
                        .HasForeignKey("StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", "MailFolder")
                        .WithMany("StoredEmails")
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", "MailFolder")
                        .WithOne("SynchronizationCheckpoint")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", "MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailChunkEntity", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSpamClassificationEntity", b =>
                {
                    b.Navigation("Signals");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmbeddingProfileEntity", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailAnsweringAuditEntryEntity", b =>
                {
                    b.Navigation("Emails");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.Navigation("StoredEmails");

                    b.Navigation("SynchronizationCheckpoint");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailRuleExecutionEntity", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", b =>
                {
                    b.Navigation("MailFolders");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Content");

                    b.Navigation("ContentRepairRequest");

                    b.Navigation("Mutations");

                    b.Navigation("SearchDocument");

                    b.Navigation("SpamClassification");
                });
#pragma warning restore 612, 618
        }
    }
}
