// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the GNU Affero General Public License, Version 3. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailFathom.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// The generated shape would have added the user column with the zero identifier as its default and then pointed a
    /// foreign key at a row nothing had inserted, which fails on any database that already holds a mailbox. The three
    /// statements between the generated operations are what make it apply forward instead: the user this deployment is
    /// already serving is provisioned, every mailbox already stored is carried onto it, and only then does the column
    /// become required and keyed. A database with no mailbox in it gets the user row all the same, because binding the
    /// first folder of a configured account reads that record rather than inventing one.
    /// </remarks>
    public partial class AddUserAccounts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "settings_accounts",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Document = table.Column<string>(type: "jsonb", nullable: false),
                    Version = table.Column<long>(type: "bigint", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_settings_accounts", x => x.Id);
                });

            // The identifier is generated by the database rather than written into this file, so no two deployments
            // share a user identity and nothing downstream can come to depend on a well-known one. The document
            // starts empty: what belongs in it is the user's mail-account declarations and settings, which are still
            // read from configuration at this release and are imported into it by the change that moves them.
            migrationBuilder.Sql(
                """
                INSERT INTO settings_accounts ("Id", "Document", "Version", "CreatedAt", "UpdatedAt")
                SELECT gen_random_uuid(), '{}'::jsonb, 1, now(), now()
                WHERE NOT EXISTS (SELECT 1 FROM settings_accounts);
                """);

            migrationBuilder.AddColumn<Guid>(
                name: "UserId",
                table: "mailbox_accounts",
                type: "uuid",
                nullable: true);

            // Every mailbox this deployment has synchronized is one user's, because that is what a deployment served
            // before this release. The subquery names the row inserted above rather than a value repeated here.
            migrationBuilder.Sql(
                """
                UPDATE mailbox_accounts
                SET "UserId" = (SELECT "Id" FROM settings_accounts ORDER BY "CreatedAt", "Id" LIMIT 1)
                WHERE "UserId" IS NULL;
                """);

            migrationBuilder.AlterColumn<Guid>(
                name: "UserId",
                table: "mailbox_accounts",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_mailbox_accounts_UserId",
                table: "mailbox_accounts",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_mailbox_accounts_settings_accounts_UserId",
                table: "mailbox_accounts",
                column: "UserId",
                principalTable: "settings_accounts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_mailbox_accounts_settings_accounts_UserId",
                table: "mailbox_accounts");

            migrationBuilder.DropTable(
                name: "settings_accounts");

            migrationBuilder.DropIndex(
                name: "IX_mailbox_accounts_UserId",
                table: "mailbox_accounts");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "mailbox_accounts");
        }
    }
}
