// <auto-generated />
using System;
using MailFathom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace MailFathom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MailFathomDbContext))]
    partial class MailFathomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.BackfillPositionEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("LastProcessedStoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("backfill_positions", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Defect")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("StoredEmailId");

                    b.ToTable("email_content_repair_requests", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<long>("MimeByteLength")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RawMime")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoredEmailId");

                    b.ToTable("email_message_contents", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", b =>
                {
                    b.Property<Guid>("StoredEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<string>("BodyTextBeforeTrimming")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParticipantAddresses")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SubjectText", "ParticipantAddresses", "BodyText" });

                    b.Property<string>("SubjectText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TextSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("StoredEmailId");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_email_search_documents_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("email_search_documents", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HierarchyDelimiter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ResolutionGeneration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MailboxAccountId", "Alias", "ResolutionGeneration")
                        .IsUnique()
                        .HasDatabaseName("ix_mail_folders_account_alias_generation");

                    b.ToTable("mail_folders", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id")
                        .HasName("PK_mailbox_accounts");

                    b.ToTable("mailbox_accounts", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<long>("AttachmentTotalSizeOctets")
                        .HasColumnType("bigint");

                    b.Property<bool>("CarriesUnverifiedSignature")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("CcAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("ContainsUnexpandedTnefPart")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentAvailability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<int>("InlineResourceCount")
                        .HasColumnType("integer");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelyFlagged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemotelySeen")
                        .HasColumnType("boolean");

                    b.Property<long>("MailFolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("MailboxAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RemoteExpungeObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RemoteFlagsObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("ReplyToAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SenderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SenderNormalizedAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SizeOctets")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ThreadReferences")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CcAddresses")
                        .HasDatabaseName("ix_stored_emails_cc_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CcAddresses"), "GIN");

                    b.HasIndex("ReplyToAddresses")
                        .HasDatabaseName("ix_stored_emails_reply_to_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ReplyToAddresses"), "GIN");

                    b.HasIndex("SenderNormalizedAddress")
                        .HasDatabaseName("ix_stored_emails_sender");

                    b.HasIndex("ToAddresses")
                        .HasDatabaseName("ix_stored_emails_to_addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ToAddresses"), "GIN");

                    b.HasIndex("MailFolderId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_stored_emails_folder_timeline");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("MailFolderId", "ReceivedAt", "Id"), new[] { NullSortOrder.Unspecified, NullSortOrder.NullsLast, NullSortOrder.Unspecified });

                    b.HasIndex("MailFolderId", "RemoteFlagsObservedAt", "Uid")
                        .HasDatabaseName("ix_stored_emails_reconciliation_queue")
                        .HasFilter("\"RemoteExpungeObservedAt\" IS NULL");

                    b.HasIndex("MailFolderId", "UidValidity", "Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_stored_emails_folder_uidvalidity_uid");

                    b.HasIndex("MailboxAccountId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_stored_emails_account_timeline");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("MailboxAccountId", "ReceivedAt", "Id"), new[] { NullSortOrder.Unspecified, NullSortOrder.NullsLast, NullSortOrder.Unspecified });

                    b.ToTable("stored_emails", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", b =>
                {
                    b.Property<long>("MailFolderId")
                        .HasColumnType("bigint");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("LastSeenUid")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("MailFolderId")
                        .HasName("pk_synchronization_checkpoints");

                    b.ToTable("synchronization_checkpoints", (string)null);
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("ContentRepairRequest")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailContentRepairRequestEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("Content")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailMessageContentEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", "StoredEmail")
                        .WithOne("SearchDocument")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.EmailSearchDocumentEntity", "StoredEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredEmail");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", "MailboxAccount")
                        .WithMany("MailFolders")
                        .HasForeignKey("MailboxAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxAccount");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", "MailFolder")
                        .WithMany("StoredEmails")
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", b =>
                {
                    b.HasOne("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", "MailFolder")
                        .WithOne("SynchronizationCheckpoint")
                        .HasForeignKey("MailFathom.Infrastructure.Persistence.Entities.SynchronizationCheckpointEntity", "MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailFolderEntity", b =>
                {
                    b.Navigation("StoredEmails");

                    b.Navigation("SynchronizationCheckpoint");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.MailboxAccountEntity", b =>
                {
                    b.Navigation("MailFolders");
                });

            modelBuilder.Entity("MailFathom.Infrastructure.Persistence.Entities.StoredEmailEntity", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("ContentRepairRequest");

                    b.Navigation("SearchDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
