// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the GNU Affero General Public License, Version 3. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using MailFathom.Application.Emails.Mailboxes;
using MailFathom.Application.Emails.Search;
using MailFathom.Domain.Emails;
using MailFathom.Infrastructure.Persistence;
using MailFathom.Infrastructure.Persistence.Connections;
using MailFathom.Infrastructure.Persistence.Emails;
using MailFathom.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace MailFathom.Infrastructure.UnitTests.Persistence.Emails;

/// <summary>
/// Asserts what the attachment-match adapter sends to PostgreSQL. The command is generated by the real provider against
/// the real model with no connection opened, which is where the two claims this adapter makes are checkable: that a
/// caller's words reach both <c>websearch_to_tsquery</c> and <c>ts_headline</c> as one parameter, and that a picture's
/// description is selected by the kind recorded on its attachment row rather than by matching those words against it.
/// Which rows the server then returns, and what the reading costs, is the integration suite's.
/// </summary>
public sealed class EmailAttachmentMatchReaderCommandTests
{
    /// <summary>A query text carrying everything an injection attempt would: quotes, a statement terminator, a comment.</summary>
    private const string HostileQueryText = "'; DROP TABLE email_attachment_texts; -- \" \\ %";

    /// <summary>Whatever a caller writes stays one value, so nothing in it can become part of the command.</summary>
    [Fact]
    public void MatchedPassagesQuery_HostileQueryText_ReachesPostgresAsAParameter()
    {
        // Act
        var command = GeneratedMatchedCommand(EmailSearchQueryText.Create(HostileQueryText));

        // Assert
        Assert.Contains(HostileQueryText, ParameterDeclarations(command), StringComparison.Ordinal);
        Assert.DoesNotContain(HostileQueryText, CommandBody(command), StringComparison.Ordinal);
        Assert.DoesNotContain("DROP TABLE", CommandBody(command), StringComparison.Ordinal);
    }

    /// <summary>
    /// The file-level vector is what narrows the walk to the attachments a query could be in, so the passages of every
    /// other file are never matched one by one. A statement that reached the chunks first would read every passage of
    /// every attachment of every ranked message.
    /// </summary>
    [Fact]
    public void MatchedPassagesQuery_AnyQuery_NarrowsByTheAttachmentIndexBeforeMatchingItsPassages()
    {
        // Act
        var statement = CommandBody(GeneratedMatchedCommand(EmailSearchQueryText.Create("invoice")));

        // Assert
        Assert.Contains(nameof(EmailAttachmentTextEntity.SearchVector), statement, StringComparison.Ordinal);
        Assert.Contains("@@", statement, StringComparison.Ordinal);
        Assert.Contains("ts_headline", statement, StringComparison.Ordinal);
    }

    /// <summary>The bounds reach the server as the option list that cuts the extracts, so PostgreSQL applies them.</summary>
    [Fact]
    public void MatchedPassagesQuery_ConfiguredSnippetBounds_ReachTheHeadlineOptions()
    {
        // Arrange
        var bounds = EmailSearchSnippetBounds.Create(snippetsPerEmail: 2, wordsPerSnippet: 15);

        // Act
        var command = GeneratedMatchedCommand(EmailSearchQueryText.Create("invoice"), bounds);

        // Assert
        Assert.Contains("MaxFragments=2", command, StringComparison.Ordinal);
        Assert.Contains("MaxWords=15", command, StringComparison.Ordinal);
        Assert.Contains("MinWords=5", command, StringComparison.Ordinal);
    }

    /// <summary>A statement with no bound would walk every passage of every attachment the window ranked.</summary>
    [Fact]
    public void MatchedPassagesQuery_AnyWindow_ClosesTheWalkWithALimit()
    {
        // Act
        var statement = CommandBody(GeneratedMatchedCommand(EmailSearchQueryText.Create("invoice")));

        // Assert
        Assert.Contains("LIMIT", statement, StringComparison.Ordinal);
    }

    /// <summary>
    /// The claim ADR 0030's floor rests on. A description is reached because its attachment row says what it is, and a
    /// query text never enters the statement at all — so no word a caller writes can pull a picture into a result by
    /// matching a sentence a model composed about it.
    /// </summary>
    [Fact]
    public void DescribedPassagesQuery_AnyWindow_SelectsByTheRecordedKindAndMatchesNoQueryText()
    {
        // Act
        var command = GeneratedDescribedCommand();

        // Assert
        Assert.Contains(nameof(EmailAttachmentTextEntity.Kind), CommandBody(command), StringComparison.Ordinal);
        Assert.DoesNotContain("websearch_to_tsquery", command, StringComparison.Ordinal);
        Assert.DoesNotContain("ts_headline", command, StringComparison.Ordinal);
        Assert.DoesNotContain("@@", command, StringComparison.Ordinal);
    }

    /// <summary>
    /// The selection narrows both statements as well as the identifiers, because PostgreSQL reads each under its own
    /// snapshot: a message that left the request's scope after the ranking is absent rather than quoted.
    /// </summary>
    [Fact]
    public void MatchedPassagesQuery_StructuralFilters_NarrowTheMessagesBeforeAnyPassageIsRead()
    {
        // Arrange
        var selection = MailboxEmailSelection.Create(
            MailboxScope.NothingReadable,
            senderAddress: "anna@example.test",
            recipientAddress: null,
            subjectFragment: null,
            receivedOnOrAfter: null,
            receivedBefore: null,
            isRemotelySeen: null,
            isRemotelyFlagged: null,
            keyword: null,
            hasAttachments: true);

        // Act
        var statement = CommandBody(
            GeneratedMatchedCommand(EmailSearchQueryText.Create("invoice"), selection: selection));

        // Assert
        Assert.Contains(nameof(StoredEmailEntity.SenderNormalizedAddress), statement, StringComparison.Ordinal);
        Assert.Contains(nameof(StoredEmailEntity.AttachmentCount), statement, StringComparison.Ordinal);
    }

    /// <summary>Gets the selection that narrows nothing, which is what a command test uses unless the filters are its subject.</summary>
    private static MailboxEmailSelection UnfilteredSelection => MailboxEmailSelection.Create(
        MailboxScope.NothingReadable,
        senderAddress: null,
        recipientAddress: null,
        subjectFragment: null,
        receivedOnOrAfter: null,
        receivedBefore: null,
        isRemotelySeen: null,
        isRemotelyFlagged: null,
        keyword: null,
        hasAttachments: null);

    private static IReadOnlyList<StoredEmailId> OneRankedEmail =>
        [StoredEmailId.Create(new Guid("00000000-0000-0000-0000-000000000001"))];

    /// <summary>Generates the passage-matching command the adapter would send, without opening a connection.</summary>
    private static string GeneratedMatchedCommand(
        EmailSearchQueryText queryText,
        EmailSearchSnippetBounds? snippetBounds = null,
        MailboxEmailSelection? selection = null)
    {
        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        var reader = new EmailAttachmentMatchReader(context, PostgresTextSearchConfiguration.Default);

        return reader
            .MatchedPassagesQuery(
                selection ?? UnfilteredSelection,
                queryText,
                snippetBounds ?? EmailSearchSnippetBounds.Default,
                OneRankedEmail)
            .ToQueryString();
    }

    /// <summary>Generates the description command the adapter would send, without opening a connection.</summary>
    private static string GeneratedDescribedCommand()
    {
        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        var reader = new EmailAttachmentMatchReader(context, PostgresTextSearchConfiguration.Default);

        return reader
            .DescribedPassagesQuery(UnfilteredSelection, EmailSearchSnippetBounds.Default, OneRankedEmail)
            .ToQueryString();
    }

    /// <summary>Drops the parameter declarations EF Core prefixes, leaving the statement those parameters are read by.</summary>
    private static string CommandBody(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? command : command[statementStart..];
    }

    /// <summary>Keeps the parameter declarations EF Core prefixes, which is where a parameterized value appears.</summary>
    private static string ParameterDeclarations(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? string.Empty : command[..statementStart];
    }
}
