// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using System.Text.RegularExpressions;
using MailFathom.Application.Emails.Mailboxes;
using MailFathom.Domain.Accounts;
using MailFathom.Domain.Emails;
using MailFathom.Infrastructure.Persistence;
using MailFathom.Infrastructure.Persistence.Emails;
using MailFathom.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace MailFathom.Infrastructure.UnitTests.Persistence.Emails;

/// <summary>
/// Asserts the shape of the command a timeline page is read with, which is what decides whether a keyset page stays
/// bounded once a scope names several accounts. The command is generated by the real provider against the real model
/// and no connection is opened; whether PostgreSQL then serves each walk from the timeline index without sorting what
/// matched is a query-plan question, and the integration suite is where that is answered against real data.
/// </summary>
/// <remarks>
/// The merge is the one composition here that a compiler cannot check. EF Core refuses a set operation whose operands
/// have already been projected, and it refuses it by throwing while translating — so a merge written the wrong way
/// round builds, passes review, and fails on the first request naming two accounts. That is the regression this class
/// exists for, and every assertion below is over a command that had to translate before it could be read.
/// </remarks>
public sealed partial class StoredEmailTimelineReaderCommandTests
{
    private const int PageLimit = 25;

    /// <summary>
    /// A scope naming one account keeps the query this read has always issued: one ordered, bounded walk. That is what
    /// "no slower for a single account" means here — the merge is not composed at all, so there is nothing extra to
    /// plan.
    /// </summary>
    [Fact]
    public void Page_AScopeNamingOneAccount_IsOneOrderedWalkRatherThanAMerge()
    {
        // Act
        var command = CommandFor("acct-1");

        // Assert
        Assert.DoesNotContain("UNION", command, StringComparison.Ordinal);
        Assert.Equal(1, Occurrences(command, "LIMIT"));
    }

    /// <summary>
    /// Several accounts are appended walks rather than one predicate over the account list, and each walk is bounded to
    /// the page it might have to supply on its own. A containment is what stops PostgreSQL deriving an ordered path
    /// from the timeline index, so what the outer ordering would otherwise sort is everything that matched instead of
    /// at most one page per account.
    /// </summary>
    [Theory]
    [InlineData(2)]
    [InlineData(3)]
    public void Page_AScopeNamingSeveralAccounts_AppendsOneBoundedWalkPerAccount(int accountsInScope)
    {
        // Arrange
        var accountIds = AccountIdentifiers(accountsInScope);

        // Act
        var command = CommandFor(accountIds);

        // Assert
        Assert.Equal(accountsInScope - 1, Occurrences(command, "UNION ALL"));
        Assert.Equal(accountsInScope, Occurrences(command, $"\"{nameof(StoredEmailEntity.MailboxAccountId)}\" = @accountId"));

        // One bound per walk and one over the merge, which is what makes the page a page rather than every account's.
        Assert.Equal(accountsInScope + 1, Occurrences(command, "LIMIT"));
    }

    /// <summary>
    /// The scope's own account list must not reach the command as a containment, because that is the predicate the
    /// merge exists to avoid. The single-account query is what states the containment, over a list of one, where the
    /// planner has an equality to work with anyway.
    /// </summary>
    [Fact]
    public void Page_AScopeNamingSeveralAccounts_NamesNoContainmentOverTheAccountList()
    {
        // Act
        var merged = CommandFor(AccountIdentifiers(3));
        var single = CommandFor("acct-1");

        // Assert
        Assert.DoesNotContain("@accountIds", merged, StringComparison.Ordinal);
        Assert.Contains("@accountIds", single, StringComparison.Ordinal);
    }

    /// <summary>
    /// The merged page has to be ordered the way a single walk is ordered, because a continuation cursor taken from a
    /// merged page is a boundary in that order: the undated key leads, the received timestamp follows, and the
    /// identifier breaks the tie. A page ordered any other way would resume somewhere else.
    /// </summary>
    [Theory]
    [InlineData(EmailTimelineDirection.NewestFirst)]
    [InlineData(EmailTimelineDirection.OldestFirst)]
    public void Page_AScopeNamingSeveralAccounts_OrdersTheMergeTheWayOneWalkIsOrdered(EmailTimelineDirection direction)
    {
        // Act
        var merged = FinalOrderingIn(CommandFor(direction, AccountIdentifiers(3)));
        var single = FinalOrderingIn(CommandFor(direction, ["acct-1"]));

        // Assert
        Assert.Equal(single, merged);
        Assert.NotEmpty(merged);
    }

    /// <summary>Names as many accounts as asked for, in the order the scope will sort them into.</summary>
    private static string[] AccountIdentifiers(int count) =>
        [.. Enumerable.Range(1, count).Select(position => $"acct-{position}")];

    /// <summary>Generates the command a page is read with, without opening a connection.</summary>
    private static string CommandFor(params string[] accountIds) =>
        CommandFor(EmailTimelineDirection.NewestFirst, accountIds);

    private static string CommandFor(EmailTimelineDirection direction, string[] accountIds)
    {
        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        var filter = EmailTimelineFilter.Create(
            MailboxScope.Create([.. accountIds.Select(MailAccountId.Create)], selectedFolders: null),
            senderAddress: null,
            recipientAddress: null,
            subjectFragment: null,
            receivedOnOrAfter: null,
            receivedBefore: null,
            isRemotelySeen: null,
            isRemotelyFlagged: null,
            keyword: null,
            hasAttachments: null,
            direction);

        return StoredEmailTimelineReader
            .Page(context.StoredEmails.AsNoTracking(), filter, continueAfter: null, PageLimit)
            .ToQueryString();
    }

    /// <summary>
    /// Keeps the last <c>ORDER BY</c> clause of a command, with the source alias each key is qualified by removed.
    /// </summary>
    /// <remarks>
    /// The claim is which expressions the page is ordered by, in which order, with which sort direction. Which alias
    /// the provider gave the subquery underneath is not part of it, and it necessarily differs between a merge and a
    /// single walk because the two have a different number of subqueries.
    /// </remarks>
    private static string FinalOrderingIn(string command)
    {
        var orderingStart = command.LastIndexOf("ORDER BY", StringComparison.Ordinal);

        return orderingStart < 0 ? string.Empty : SourceAlias().Replace(command[orderingStart..], string.Empty);
    }

    private static int Occurrences(string command, string fragment)
    {
        var found = 0;
        for (var index = command.IndexOf(fragment, StringComparison.Ordinal);
            index >= 0;
            index = command.IndexOf(fragment, index + fragment.Length, StringComparison.Ordinal))
        {
            found++;
        }

        return found;
    }

    /// <summary>Matches the alias a generated subquery is named by, which prefixes every column the outer query reads.</summary>
    [GeneratedRegex("""\b[a-z]\d*\.""")]
    private static partial Regex SourceAlias();
}
