#!/usr/bin/env bash
set -euo pipefail

# Regenerates the single baseline migration from the current EF Core model, through the Aspire orchestration.
#
# Development only, and it destroys local data: the database is dropped and recreated with the regenerated migration
# applied. While MailMcp is pre-release the repository keeps exactly one migration, so a model change replaces it rather
# than adding to it. See .claude/skills/add-migration/SKILL.md for why, and for the review this script does not do.
#
# The script is deliberately not a substitute for reading the result. It stops after applying the migration and leaves
# the schema dump for a human to read; nothing here decides that a migration is correct.

app_host_project='src/AppHost/AppHost.csproj'
startup_project='src/Host/Host.csproj'
migrations_directory='src/Infrastructure/Persistence/Migrations'
migration_resource='mailmcp-migrations'
migration_name='Initial'

if ! repository_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  printf 'regenerate-migration.sh must run inside a Git worktree.\n' >&2
  exit 1
fi

cd "$repository_root"

report() {
  printf '\n▸ %s\n' "$1"
}

# The startup project is what dotnet-ef loads MailMcp.Infrastructure.dll from, so building Infrastructure alone would
# leave a stale assembly there and the tool would read the model and the migration list the previous build produced.
build_startup_project() {
  dotnet build "$startup_project" --nologo --verbosity quiet
}

run_migration_command() {
  aspire resource "$migration_resource" "$1" --apphost "$app_host_project" --non-interactive --nologo "${@:2}"
}

# EF's generator writes no file header, and IDE0073 is an error in this directory like everywhere else. The formatter
# carries the code fix for it, so nothing here hand-edits generated output — but it has to run now rather than being
# left to the verification loop, because that loop formats only after a successful build and a missing header is what
# fails the build.
#
# Two details decide whether this works at all. The solution is the scope, because these files belong to Infrastructure
# and an --include filter evaluated against another project's workspace silently matches nothing. And the files are
# named individually, because --include given the directory matches nothing either. Only the migration itself is
# affected: EF marks the designer file and the model snapshot `<auto-generated />`, which IDE0073 skips.
write_the_file_header() {
  dotnet format MailMcp.slnx --no-restore --include "$migrations_directory"/*.cs
}

resource_states() {
  aspire describe --apphost "$app_host_project" --non-interactive --nologo 2>/dev/null \
    | sed -e 's/\x1b\[[0-9;]*m//g' -e 's/\x1b\]8;[^\\]*\\//g'
}

# Starting an orchestration that is already running costs a full AppHost build for nothing, which is the single largest
# cost in this workflow. A run that reuses one is the common case while iterating on a model.
ensure_orchestration_is_running() {
  if resource_states | grep -qE "^\│ ${migration_resource}"; then
    report 'Reusing the running orchestration.'
    return
  fi

  report 'Starting the orchestration.'
  ASPIRE_CLI_START_TIMEOUT="${ASPIRE_CLI_START_TIMEOUT:-300}" \
    aspire start --apphost "$app_host_project" --non-interactive --nologo >/dev/null
}

wait_for_a_healthy_database() {
  report 'Waiting for PostgreSQL to become healthy.'

  for _ in $(seq 1 60); do
    if resource_states | grep -qE "^\│ mailmcp .*Healthy"; then
      return
    fi

    sleep 3
  done

  printf 'The mailmcp database resource did not become healthy. Read `aspire logs postgres`; a password authentication failure means the data volume and the generated password have diverged.\n' >&2
  exit 1
}

# RunDatabaseUpdateOnStart applies whatever migration currently exists when the AppHost starts, and the resource refuses
# a second command while that one runs. Waiting for it to settle is what keeps a run from failing with "Another command
# is already running on this resource". A failed startup update is fine to proceed from: this script is about to
# discard the migration it failed on.
wait_for_the_migration_resource_to_settle() {
  report 'Waiting for the startup migration run to settle.'

  for _ in $(seq 1 60); do
    if resource_states | grep -qE "^\│ ${migration_resource} .*(Finished|FailedToStart)"; then
      return
    fi

    sleep 3
  done

  printf 'The %s resource is still busy. Read `aspire logs %s`.\n' "$migration_resource" "$migration_resource" >&2
  exit 1
}

# Before anything is built, and before the orchestration is started, for two reasons. Starting it builds the AppHost,
# which compiles Infrastructure, so a migration left behind by an interrupted run — one generated but not yet given its
# file header — would fail that build and leave the script unable to reach the step that repairs it. And the migration
# is about to be replaced regardless, so applying it on startup would be work done to be undone.
#
# The .cs files only. The directory also holds a hand-written .editorconfig that relaxes the two diagnostics EF's
# generator trips, and removing it would turn the regenerated file into build errors.
report 'Discarding the existing migration.'
rm -f "${migrations_directory:?}"/*.cs

ensure_orchestration_is_running
wait_for_a_healthy_database
wait_for_the_migration_resource_to_settle

report 'Rebuilding so the tool sees an assembly with no migrations in it.'
build_startup_project

report "Generating the ${migration_name} migration."
run_migration_command ef-migrations-add -- --name "$migration_name"

report 'Writing the copyright and license header into the generated files.'
write_the_file_header

report 'Rebuilding so the tool applies what is in the assembly.'
build_startup_project

# Reset rather than drop-then-update: Drop Database leaves the mailmcp resource unhealthy, and every later command waits
# for that resource to become healthy, so the command that would recreate the database would wait on itself forever.
report 'Dropping and recreating the database with the regenerated migration applied.'
run_migration_command ef-database-reset

report 'Done. Review the schema before committing:'
printf '\n    scripts/dump-local-schema.sh\n\n'
