// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the GNU Affero General Public License, Version 3. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

namespace MailFathom.SyntheticMail.Corpus;

/// <summary>What an exported corpus carries beside its messages.</summary>
/// <param name="Invocation">The invocation that produced the corpus, as the run that exported it reported.</param>
/// <param name="Exchanges">The message file names, grouped into exchanges and each exchange oldest turn first.</param>
/// <remarks>
/// <para>
/// Two things and no more, because everything else about a message is in the message. The invocation is what makes a
/// corpus answerable — which seed, which languages, which topics, how many, over what range — and a second corpus is
/// generated by editing that line rather than by reconstructing it from a listing.
/// </para>
/// <para>
/// The grouping is here because it is the one thing the messages cannot say. Which turn a message is decides how it
/// is delivered — submitted by the sending account or appended to the mailbox's own Sent folder — and it alternates
/// from the correspondent onwards, so a position in an exchange answers it while an ancestry header does not: the
/// ancestry an exported message carries is the one the seed proposed, and delivery replaces it with the identifiers
/// the mailbox actually assigned.
/// </para>
/// <para>
/// Both are nullable because this is what is read from a file somebody may have edited, and a corpus missing either
/// is refused where it is read with a message naming what is missing.
/// </para>
/// </remarks>
internal sealed record CorpusManifest(string? Invocation, IReadOnlyList<IReadOnlyList<string>>? Exchanges);
