// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using MailFathom.Application.Emails.Embeddings;
using MailFathom.Application.Emails.Mailboxes;
using MailFathom.Infrastructure.Persistence;
using MailFathom.Infrastructure.Persistence.Embeddings;
using MailFathom.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace MailFathom.Infrastructure.UnitTests.Persistence.Embeddings;

/// <summary>
/// Asserts what the vector search adapter actually sends to PostgreSQL. The command is generated by the real provider
/// against the real model and no connection is opened, which is the only place without a database where the query is
/// known to translate at all: a distance operator, a join, and a grouped minimum are each a translation the provider
/// can refuse at runtime, and a fake index would answer whatever the test arranged instead.
/// </summary>
public sealed class EmailVectorSearchIndexReaderCommandTests
{
    private static readonly EmbeddingProfileId ProfileId =
        EmbeddingProfileId.Create(new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"));

    /// <summary>Each metric has an operator of its own, and indexing under the wrong one returns a number rather than an error.</summary>
    [Theory]
    [InlineData(EmbeddingDistanceMetric.Cosine, "<=>")]
    [InlineData(EmbeddingDistanceMetric.InnerProduct, "<#>")]
    [InlineData(EmbeddingDistanceMetric.EuclideanDistance, "<->")]
    public void NearestHitsQuery_ProfileMetric_MeasuresWithThatMetricsOperator(
        EmbeddingDistanceMetric distanceMetric,
        string vectorOperator)
    {
        // Act
        var command = GeneratedCommand(distanceMetric);

        // Assert
        Assert.Contains(vectorOperator, command, StringComparison.Ordinal);
    }

    /// <summary>A metric no operator serves is refused rather than defaulted, because the wrong one fails silently.</summary>
    [Fact]
    public void NearestHitsQuery_MetricWithNoOperator_IsRefused()
    {
        // Act, Assert
        Assert.Throws<ArgumentOutOfRangeException>(() => GeneratedCommand((EmbeddingDistanceMetric)(-1)));
    }

    /// <summary>The query vector is a value a request produced, so it reaches PostgreSQL the way every other one does.</summary>
    [Fact]
    public void NearestHitsQuery_AnyQueryVector_ReachesPostgresAsAParameter()
    {
        // Act
        var command = GeneratedCommand(EmbeddingDistanceMetric.Cosine);
        var statement = CommandBody(command);

        // Assert
        Assert.Contains("@target", ParameterDeclarations(command), StringComparison.Ordinal);
        Assert.Contains("@target", statement, StringComparison.Ordinal);
        Assert.DoesNotContain("0.1,0.2", statement, StringComparison.Ordinal);
    }

    /// <summary>A message appears once however many of its passages are near, scored by its nearest one.</summary>
    [Fact]
    public void NearestHitsQuery_AnyQuery_ScoresEachEmailByItsNearestPassageAndBoundsTheWindow()
    {
        // Act
        var statement = CommandBody(GeneratedCommand(EmbeddingDistanceMetric.Cosine));

        // Assert
        Assert.Contains("min(", statement, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("email_chunks", statement, StringComparison.Ordinal);
        Assert.Contains("LIMIT", statement, StringComparison.Ordinal);
    }

    /// <summary>
    /// Distance alone is not a total order. Near-duplicate mail — and any deterministic generator — ties, and an
    /// unbroken tie leaves the server free to return either order, so two identical searches would disagree about what
    /// the nearest results were and the fused order built on top of them would inherit that. The window is therefore cut
    /// by the same timeline key the lexical ranking appends.
    /// </summary>
    [Fact]
    public void NearestHitsQuery_DistanceTies_AreBrokenByTheTimelineKeyBeforeTheWindowIsCut()
    {
        // Act
        var ordering = WindowOrdering(CommandBody(GeneratedCommand(EmbeddingDistanceMetric.Cosine)));

        // Assert
        Assert.Contains("<=>", ordering, StringComparison.Ordinal);
        Assert.Contains(nameof(StoredEmailEntity.ReceivedAt), ordering, StringComparison.Ordinal);
        Assert.Contains(nameof(StoredEmailEntity.Id), ordering, StringComparison.Ordinal);
        Assert.True(
            ordering.IndexOf("<=>", StringComparison.Ordinal)
            < ordering.IndexOf(nameof(StoredEmailEntity.ReceivedAt), StringComparison.Ordinal),
            "The distance ranks the window and the timeline key only breaks its ties, so it has to be ordered on first.");
    }

    /// <summary>The structured filters join the ranking, so mail outside the caller's scope never takes part in it.</summary>
    [Fact]
    public void NearestHitsQuery_StructuralFilters_NarrowTheQueryBeforeAnyDistanceIsMeasured()
    {
        // Arrange
        var selection = MailboxEmailSelection.Create(
            MailboxScope.NothingReadable,
            senderAddress: "anna@example.test",
            recipientAddress: null,
            subjectFragment: null,
            receivedOnOrAfter: null,
            receivedBefore: null,
            isRemotelySeen: null,
            isRemotelyFlagged: null,
            keyword: null,
            hasAttachments: true);

        // Act
        var command = GeneratedCommand(EmbeddingDistanceMetric.Cosine, selection);

        // Assert
        Assert.Contains(nameof(StoredEmailEntity.SenderNormalizedAddress), command, StringComparison.Ordinal);
        Assert.Contains(nameof(StoredEmailEntity.AttachmentCount), command, StringComparison.Ordinal);
    }

    /// <summary>Vectors of another profile belong to another space, so they are excluded rather than ranked far away.</summary>
    [Fact]
    public void NearestHitsQuery_AnyQuery_ReadsOnlyTheActiveProfilesVectors()
    {
        // Act
        var command = GeneratedCommand(EmbeddingDistanceMetric.Cosine);

        // Assert
        Assert.Contains(nameof(EmailEmbeddingEntity.EmbeddingProfileId), command, StringComparison.Ordinal);
    }

    /// <summary>Generates the command the adapter would send, without opening a connection.</summary>
    private static string GeneratedCommand(
        EmbeddingDistanceMetric distanceMetric,
        MailboxEmailSelection? selection = null)
    {
        using var context = new MailFathomDbContextDesignTimeFactory().CreateDbContext([]);

        var reader = new EmailVectorSearchIndexReader(context);

        return reader
            .NearestHitsQuery(
                selection ?? UnfilteredSelection,
                new RegisteredEmbeddingProfile(ProfileId, IdentityWith(distanceMetric)),
                EmbeddingVector.Create([0.1f, 0.2f, 0.3f, 0.4f, 0.5f, 0.6f, 0.7f, 0.8f]),
                limit: 20)
            .ToQueryString();
    }

    private static EmbeddingProfileIdentity IdentityWith(EmbeddingDistanceMetric distanceMetric) =>
        EmbeddingProfileIdentity.Create(
            "a-provider",
            "a-model",
            modelVersion: null,
            dimension: 8,
            distanceMetric,
            EmbeddingInputPreparation.Create(2_000, passageInstruction: null, normalizesVector: true));

    /// <summary>Takes the ordering clause the window is actually cut by, which is the one the row limit follows.</summary>
    /// <remarks>
    /// Located from the limit backwards rather than by counting clauses, because the provider is free to nest the
    /// ranking in a subquery and repeat the ordering outside it. The clause that decides which rows survive is the one
    /// immediately before <c>LIMIT</c> whatever shape the rest of the statement takes.
    /// </remarks>
    private static string WindowOrdering(string statement)
    {
        var limitAt = statement.IndexOf("LIMIT", StringComparison.Ordinal);
        Assert.True(limitAt > 0, "The window is closed by a row limit.");

        var orderingAt = statement.LastIndexOf("ORDER BY", limitAt, StringComparison.Ordinal);
        Assert.True(orderingAt > 0, "The window the limit cuts is ordered before it is cut.");

        return statement[orderingAt..limitAt];
    }

    /// <summary>Drops the parameter declarations EF Core prefixes, leaving the statement those parameters are read by.</summary>
    private static string CommandBody(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? command : command[statementStart..];
    }

    /// <summary>Keeps the parameter declarations EF Core prefixes, which is where a parameterized value appears.</summary>
    private static string ParameterDeclarations(string command)
    {
        var statementStart = command.IndexOf("SELECT", StringComparison.Ordinal);

        return statementStart < 0 ? string.Empty : command[..statementStart];
    }

    /// <summary>Gets the selection that narrows nothing, which is what a command test uses unless the filters are its subject.</summary>
    private static MailboxEmailSelection UnfilteredSelection => MailboxEmailSelection.Create(
        MailboxScope.NothingReadable,
        senderAddress: null,
        recipientAddress: null,
        subjectFragment: null,
        receivedOnOrAfter: null,
        receivedBefore: null,
        isRemotelySeen: null,
        isRemotelyFlagged: null,
        keyword: null,
        hasAttachments: null);
}
