// Copyright © 2026 Krzysztof Kasprowicz
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
// Project repository: https://github.com/Krzysztof318/MailFathom

using MailFathom.Application.Access;
using MailFathom.Domain.Access;

namespace MailFathom.IntegrationTests.Orchestration;

/// <summary>Names the owner this suite's deployment serves, which every account it declares and every contact it writes belongs to.</summary>
/// <remarks>
/// <para>
/// A composed host resolves this from its owner records while it starts, and so does this harness: the owner is read
/// out of the database once the orchestration's migrations have run, rather than being an identifier stated here. It
/// has to be the persisted one because rows now key onto it — a contact's owner is a foreign key onto the owner record
/// — so a stated identifier would name an owner the database does not hold and every write of one would be refused.
/// </para>
/// <para>
/// The owner is written once from the harness's own start and read from every test's scope afterwards, and both take
/// the same lock, exactly as the host's own holder does: the write is one assignment but the value is a multi-field
/// struct, so nothing about a bare field would establish that a thread observing the write observes the whole of it.
/// </para>
/// </remarks>
internal sealed class OrchestratedDeploymentOwner : IDeploymentMailOwnerSource
{
    private readonly Lock mutex = new();

    /// <summary>The owner read out of the database, or nothing while the harness has not started.</summary>
    private MailOwnerId? resolvedOwner;

    /// <summary>Gets the one holder this suite reads, because the suite holds one database and it holds one owner.</summary>
    /// <remarks>
    /// The identifier is generated by the migration that provisions the owner record, so it is different in every
    /// database and cannot be stated. Every composed services instance therefore writes the same value back here from
    /// the same read, and an arrangement helper that names the account outside a scope resolves the owner through this
    /// rather than being handed one.
    /// </remarks>
    internal static OrchestratedDeploymentOwner Shared { get; } = new();

    /// <inheritdoc />
    /// <exception cref="InvalidOperationException">Thrown when the harness has not yet read the owner the database holds.</exception>
    public MailOwnerId Owner
    {
        get
        {
            lock (this.mutex)
            {
                return this.resolvedOwner
                    ?? throw new InvalidOperationException(
                        "The owner this harness serves is read before the composed services have established it.");
            }
        }
    }

    /// <summary>States the owner the harness read out of the database, which is the one owner it holds.</summary>
    /// <param name="owner">The owner every account and every contact of this deployment belongs to.</param>
    /// <exception cref="ArgumentException">Thrown when <paramref name="owner" /> names nobody.</exception>
    internal void Resolved(MailOwnerId owner)
    {
        if (!owner.IsSpecified)
        {
            throw new ArgumentException("The owner a deployment serves is a named one.", nameof(owner));
        }

        lock (this.mutex)
        {
            this.resolvedOwner = owner;
        }
    }
}
